### PR TITLE
Correct detection of anonymous AMD modules

### LINKED ISSUE #140: Issue with jquery-ui-effect (Magento 2.4.4)
Edit 03/05/2022 : 
Just remove the two files from the magepack.config.js to solve the issue...

Good afternoon,

I have a situation with your wonderful extension and the new released magento 2.4.4 version.
Indeed, the two files from jquery-ui updated framework :

1. [lib/web/jquery/ui-modules/effects/effect-fade.js](https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/ui-modules/effects/effect-fade.js)
2. [lib/web/jquery/ui-modules/effects/effect-blind.js](https://github.com/magento/magento2/blob/2.4-develop/lib/web/jquery/ui-modules/effects/effect-blind.js)

Which were reworked from the previous version, throws an error only when I magepack them (with the standard minification and bundle I do not have any issue).

This is the error I have in my developer console for the homepage : 
`Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("fade","toggle",(function(e,t){var n="show"===e.mode;$(this).css("opacity",n?0:1).animate({opacity:n?1:0},{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}`

This error is also throwed by blind effect.

So far, I can either remove them from the magepack.config.js (requirejs we will download them as standalone version) or correct them manually by naming them.

Exemple for effect-fade.js : 
```

/*!
 * jQuery UI Effects Fade 1.13.0
 * http://jqueryui.com
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license.
 * http://jquery.org/license
 */

//>>label: Fade Effect
//>>group: Effects
//>>description: Fades the element.
//>>docs: http://api.jqueryui.com/fade-effect/
//>>demos: http://jqueryui.com/effect/

( function( factory ) {
	"use strict";

	if ( typeof define === "function" && define.amd ) {

		// AMD. Naming the module
		define('jquery-ui-effect-fade', [
		// AMD. Register as an anonymous module.
		//define( [
			"jquery",
			"../version",
			"../effect"
		], factory );
	} else {

		// Browser globals
		factory( jQuery );
	}
} )( function( $ ) {
"use strict";

return $.effects.define( "fade", "toggle", function( options, done ) {
	var show = options.mode === "show";

	$( this )
		.css( "opacity", show ? 0 : 1 )
		.animate( {
			opacity: show ? 1 : 0
		}, {
			queue: false,
			duration: options.duration,
			easing: options.easing,
			complete: done
		} );
} );

} );

```

These two JS files are used for : 

- fade.js for minicart
- blind.js for message 

a Pull Request advice to suppress them for the native code of Magento for native CSS Transition and native function from jQuery itself : [https://github.com/magento/magento2/pull/32886](https://github.com/magento/magento2/pull/32886)

Not sure if this error come from our current configuration as it heavy customized,

Did you meet this issue also on Magento 2.4.4 ?

Magento 2.4.4 have also a mapping error for Magento_Theme module (which is not related to my current issue) : 
[https://github.com/magento/magento2/issues/35327](https://github.com/magento/magento2/issues/35327)

### LINKED ISSUE #154: Error javascript after bundling process
Hello,

I have this error after bundling process and enable:

image

I have tried nodejs V14, and V16.

Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("blind","hide",(function(e,t){var i={up:["bottom","top"],vertical:["bottom","top"],down:["top","bottom"],left:["right","left"],horizontal:["right","left"],right:["left","right"]},n=$(this),o=e.direction||"up",r=n.cssClip(),s={clip:$.extend({},r)},a=$.effects.createPlaceholder(n);s.clip[i[o][0]]=s.clip[i[o][1]],"show"===e.mode&&(n.cssClip(s.clip),a&&a.css($.effects.clipToBox(s)),s.clip=r),a&&a.animate($.effects.clipToBox(s),e.duration,e.easing),n.animate(s,{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.min.js:17:53)
    at intakeDefines (require.min.js:81:132)
    at localRequire (require.min.js:104:1)
    at Object.load (mixins.min.js:8:135)
    at Module.<anonymous> (require.min.js:74:105)
    at require.min.js:12:51
    at on (require.min.js:42:147)
    at Module.callPlugin (require.min.js:64:264)
    at Module.fetch (require.min.js:58:269)
    at Module.check (require.min.js:59:162)
require.min.js:14 Uncaught Error: Mismatched anonymous define() module: function($){"use strict";return $.effects.define("fade","toggle",(function(e,t){var i="show"===e.mode;$(this).css("opacity",i?0:1).animate({opacity:i?1:0},{queue:!1,duration:e.duration,easing:e.easing,complete:t})}))}
https://requirejs.org/docs/errors.html#mismatch
    at makeError (require.min.js:17:53)
    at intakeDefines (require.min.js:81:132)
    at localRequire (require.min.js:104:1)
    at defContext.require (mixins.min.js:11:401)
    at requirejs (require.min.js:123:16)
    at (index):3911:5
bundle-common.min.js:1 JQMIGRATE: Migrate is installed, version 3.3.2
vimeo-wrapper.min.js:1          Failed to load resource: the server responded with a status of 404 ()
require.min.js:14 Uncaught Error: Script error for "vimeo/player/vimeo-wrapper"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:17:53)
    at HTMLScriptElement.onScriptError (require.min.js:117:697)
player.min.js:1          Failed to load resource: the server responded with a status of 404 ()
require.min.js:14 Uncaught Error: Script error for "vimeo/player/player"
https://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:17:53)
    at HTMLScriptElement.onScriptError (require.min.js:117:697)

I have dissable buildling awaiting solution.

### PR DESCRIPTION
**Pull request by fredden**
Fixes #140.
Fixes #154.

The existing / old regular expression is finding this on [line 35](https://github.com/magento/magento2/blob/2.4.4/lib/web/jquery/ui-modules/effects/effect-fade.js#L35): 
`return $.effects.define( "fade", "toggle", function( options, done ) {`
and matching `define( "` and treating this as a named AMD module (called 'fade'), however it should have been looking for / found this on [line 22](https://github.com/magento/magento2/blob/2.4.4/lib/web/jquery/ui-modules/effects/effect-fade.js#L22):
`define( [`
and treated this file as an anonymous AMD module and therefore named it in the bundle.

This pull request corrects the regular expression so that line 22 is found / observed and line 35 is ignored.

### CODE REVIEW

File: lib/bundle/moduleWrapper.js [hunk 1]
```diff
@@ -59,7 +60,10 @@ const isAnonymousAmd = (moduleContents) =>
  * @param {string} moduleContents Contents of the module to wrap.
  */
 const wrapAnonymousAmd = (moduleName, moduleContents) =>
-    moduleContents.replace(/define\s*\(/m, `define('${moduleName}', `);
+    moduleContents.replace(
+        /(^|\s+|;)define\s*\(/m,
+        `\n;define('${moduleName}', `
```
Comment (adamj88) [inline lib/bundle/moduleWrapper.js:65]: This line is causing a problem when adding the `;` when we have a webpack module loaded like so:

```
(function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory(require("jquery"));
    else if(typeof define === 'function' && define.amd)
        define(["jquery"], factory);
    else if(typeof exports === 'object')
        exports["module.name"] = factory(require("jquery"));
    else
        ...
```

We end up with this occurring:

```diff
    (function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory(require("jquery"));
    else if(typeof define === 'function' && define.amd)
-        define('module/path/here', ["jquery"], factory);
+;define('module/path/here, ["jquery"], factory);
    else if(typeof exports === 'object')
        exports["module.name"] = factory(require("jquery"));
    else
        ...
```

Which in turn produces the below error in the bundled JS due to it being invalid JS:

```
Uncaught SyntaxError: Unexpected token 'else' (at bundle-common.js:42559:2)
```

Comment (fredden) [reply lib/bundle/moduleWrapper.js:65]: Thanks for the feedback. I didn't consider the case where you're missing braces. I guess it's been a while since I worked with Python as my day job. I'll update the pull request to account for this case.

Comment (fredden) [reply lib/bundle/moduleWrapper.js]: @adamj88 Please can you test again?

**Comment by krzksz** [comment]
Hey @fredden, thanks for contributing. Unfortunately I didn't notice your PR before pushing my fix (I don't have much time to spend on Magepack anymore). I also added additional tests and my solution is a bit different so I hope you don't mind.

**Comment by fredden** [comment]
Hi @krzksz. Thanks for your update. Please can you re-open this pull request; I don't seem to have the permissions to do so myself.

> my solution is a bit different

I've found 3ecd854697b2c29f717293416ee6b2e2c45641a1 which is what I assume you're referring to. This looks like a great start, but doesn't solve the problem. It does solve the one case that's been reported, but won't fix cases where other syntax is used which happens to (still) match the regular expression (like `SomeObject.redefine('hats', ...`).

> I also added additional tests

Thanks for the tip about the tests. When you've reopened this pull request I'll update the tests to cover more cases so this can be resolved properly. (If I modify the branch before you reopen this, then (I think that) GitHub will force us to create a new pull request instead.)

> Unfortunately I didn't notice your PR before pushing my fix (I don't have much time to spend on Magepack anymore).

I'm sure there are people who are willing to help maintain this project (like myself). Feel free to open a discussion on GitHub or reach out individually if you'd like to discuss how that might work.

**Comment by krzksz** [comment]
Nice, opening right away! Having tests is critical for me right now as it makes testing and fixing things much quicker.

**Comment by fredden** [comment]
@krzksz I've worked out how to run the test suite (`yarn run jest`), and added tests to cover this change. I confirmed that the default branch fails with these new tests. I have also opened #160 to run the test suite in a GitHub Action (like is done for `eslint`) going forward.
